postgres:
  image: postgres:16-alpine
  container_name: postgres
  environment:
    - POSTGRES_DB=rankdrop
    - POSTGRES_USER=rankdrop
    - POSTGRES_PASSWORD=rankdrop
  volumes:
    - ./data:/var/lib/postgresql/data
  ports:
    - "5433:5432"   # optional if you want host access
  restart: unless-stopped
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U rankdrop" ]
    interval: 10s
    timeout: 5s
    retries: 5